### PR TITLE
[All habits] Fix GET/habit/assign/{habitId}/more endpoint

### LINKED ISSUE #5510: [All habits] Fix GET/habit/assign/{habitId}/more endpoint
**Environment:** OS, browser, it's version, device (for mobile devices).
**Reproducible:** always.
**Build found:** 20.03.2023

**Preconditions**
User is authorized
User has at least two habit with AQUIRED and INPROGRESS status.

**Steps to reproduce**
1. Go to GreenCity Swagger
2. Use [/habit/assign/{habitId}/more](http://localhost:8080/swagger-ui.html#/operations/habit-assign-controller/getUsersHabitByHabitIdUsingGET)

**Actual result**
500 error
image

**Expected result**
Return info about habit assign

### PR DESCRIPTION
**Pull request by sergoliarnik**
## Summary Of Issue :
Need to fix bug with GET/habit/assign/{habitId}/more endpoint

**Issue Link**
https://github.com/ita-social-projects/GreenCity/issues/5510

## Summary Of Changes :
1) added new findByHabitAssignIdAndUserId repo method
2) removed findByUserIdAndHabitId repo method that is not used anywhere
3) refactor getUsersHabitByHabitAssignId controller method and findHabitByUserIdAndHabitAssignId repo method
4) refactor tests

## CHECK LIST
- [x] Code is up-to-date with the `dev` branch.
- [x] You've successfully built and run the tests locally.
- [x] There are new or updated unit tests validating the change.
- [x] JIRA/ Github Issue number & title in PR title (ISSUE-: Ticket title)
- [x] This template filled (above this section).
- [x] Sonar's report does not contain bugs, vulnerabilities, security issues, code smells ar duplication
- [ ] `NEED_REVIEW` and `READY_FOR_REVIEW` labels are added.
- [x] All files reviewed before sending to reviewers

### CODE REVIEW

File: dao/src/main/java/greencity/repository/HabitAssignRepo.java [hunk 1]
```diff
@@ -245,4 +236,19 @@ List<HabitAssign> findAllHabitAssignsByStatusAndHabitId(@Param("status") HabitAs
...
+     * @param habitAssignId {@link Long} id.
+     * @param userId        {@link Long} id.
+     * @return {@link HabitAssign} instance.
+     */
+    @Query(value = "FROM HabitAssign ha"
+        + " JOIN FETCH ha.habit h JOIN FETCH h.habitTranslations ht"
+        + " JOIN FETCH ht.language l"
+        + " WHERE ha.id = :habitAssignId AND ha.user.id = :userId"
+        + " AND upper(ha.status) NOT IN ('CANCELLED','EXPIRED')")
+    Optional<HabitAssign> findByHabitAssignIdAndUserId(Long habitAssignId, Long userId);
```
Comment (RomaMocherniuk) [inline dao/src/main/java/greencity/repository/HabitAssignRepo.java:253]: why

File: core/src/main/java/greencity/controller/HabitAssignController.java [hunk 2]
```diff
@@ -255,29 +255,30 @@ public ResponseEntity<HabitAssignDto> getHabitAssignByHabitId(
...
     @ApiResponses(value = {
         @ApiResponse(code = 200, message = HttpStatuses.OK, response = HabitDto.class),
         @ApiResponse(code = 400, message = HttpStatuses.BAD_REQUEST),
         @ApiResponse(code = 401, message = HttpStatuses.UNAUTHORIZED),
         @ApiResponse(code = 404, message = HttpStatuses.NOT_FOUND)
     })
     @ApiLocale
-    @GetMapping("/{habitId}/more")
-    public ResponseEntity<HabitDto> getUsersHabitByHabitId(
+    @GetMapping("/{habitAssignId}/more")
```
Comment (RomaMocherniuk) [inline core/src/main/java/greencity/controller/HabitAssignController.java:274]: please update security config

**Review by RomaMocherniuk — APPROVED** [review]

**Review by KharchenkoV — APPROVED** [review]

**Review by MaksymGolik — APPROVED** [review]

**Review by juseti — APPROVED** [review]

**Review by ABbondar — APPROVED** [review]
