### PR TITLE
replace second parameter of ratingCalculation() metod from type 'EcoN…

### LINKED ISSUE #8070: [Affected functionality] Clear and concise summary, e.g. "[Create news] 'Publish' button is not displayed on the 'Preview' page" Fix adding eco-news in admin panel
If super admin try to create new eco-news then it has no results, but in logs as you can see on the video there is an error:  "Cannot invoke "java.lang.Double.doubleValue()" because the return value of "greencity.dto.user.UserVO.getRating()" is null] with root cause".

**Steps to reproduce**
1. Go to Admin panel on GreenCity,
2. Click on Eco news,
3. Click on button add Eco news,
4. fill all fild thet is required,
5. Click on Add.

**Actual result**
Nothing happened
In logs there is an error   Cannot invoke "java.lang.Double.doubleValue()" because the return value of "greencity.dto.user.UserVO.getRating()" is null] with root cause.

**Expected result**
Eco news will be added sacsesfuly and seved in to DB.

https://github.com/user-attachments/assets/454a5e46-8c2b-4d0e-b757-6a52f6a0c755

### PR DESCRIPTION
**Pull request by Warded120**
Issue Link: https://github.com/ita-social-projects/GreenCity/issues/8070

Changes:

- now passing the second parameter as 'UserVO' instead of mapping from type 'Econews' to 'UserVO' in ratingCalculation() metod

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved consistency in user rating calculation method in EcoNews service by standardizing the reference to rating point names.
  
- **New Features**
  - Introduced a new utility class for rating point action constants, including identifiers for news creation and undoing actions.

### CODE REVIEW

**Review by LazarenkoDmytro — APPROVED** [review]

**Review by Cr1stal423 — APPROVED** [review]

File: service/src/main/java/greencity/service/EcoNewsServiceImpl.java [hunk 1]
```diff
@@ -103,7 +103,7 @@ public AddEcoNewsDtoResponse save(AddEcoNewsDtoRequest addEcoNewsDtoRequest,
         achievementCalculation
             .calculateAchievement(userVO, AchievementCategoryType.CREATE_NEWS, AchievementAction.ASSIGN);
         ratingCalculation.ratingCalculation(ratingPointsRepo.findByNameOrThrow("CREATE_NEWS"),
-            modelMapper.map(toSave, UserVO.class));
+            userVO);
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/EcoNewsServiceImpl.java]: do you have tests for this method?
If you have please update them otherwise add tests

File: service/src/main/java/greencity/service/EcoNewsServiceImpl.java [hunk 2]
```diff
@@ -103,7 +103,7 @@ public AddEcoNewsDtoResponse save(AddEcoNewsDtoRequest addEcoNewsDtoRequest,
         achievementCalculation
             .calculateAchievement(userVO, AchievementCategoryType.CREATE_NEWS, AchievementAction.ASSIGN);
         ratingCalculation.ratingCalculation(ratingPointsRepo.findByNameOrThrow("CREATE_NEWS"),
-            modelMapper.map(toSave, UserVO.class));
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/EcoNewsServiceImpl.java]: please move `CREATE_NEWS` to the constant

**Review by LazarenkoDmytro — APPROVED** [review]

**Review by ChernenkoVitaliy — APPROVED** [review]
