### PR TITLE
Bugfix #7319 - Fixed incorrect saving for HabitTranslation for ua fields.

### LINKED ISSUE #7319: Habit Translations: ua fields doesn`t save
Environment: Windows 10, Swagger
Reproducible: always

**Preconditions**

The user is logged in

**Steps to reproduce**

habit-controller -> /habit/custom 

**Actual result**

nameUa, descriptionUa, habitItemUa are not saved in DB

**Expected result**

all fields are saved in DB

Image Image

### PR DESCRIPTION
**Pull request by ChernenkoVitaliy**
# GreenCity PR
## Issue Link 📋
https://github.com/ita-social-projects/GreenCity/issues/7319

## Added

- Added _getHabitTranslationDtoEnAndUa_ method in ModelUtils; 
- Added `@NotBlank` annotation in HabitTranslationDto for description, languageCode and name fields; 
- Added `@Valid `annotation for validation HabitTranslationDto into CustomHabitDtoRequest;
- Added _convertUa_() and _mapAllToList_() methods into HabitTranslationMapper; 
- Added necessary tests in HabitTranslationMapperTests;

## Changed

- Changed functionality  of method saveHabitTranslationListsToHabitTranslationRepo in HabitServiceImpl;
- Modified tests according to change in method _saveHabitTranslationListsToHabitTranslationRepo_ in HabitServiceImplTests;

## Summary Of Changes 🔥
Improvement according to task https://github.com/ita-social-projects/GreenCity/issues/7319;
Fixed main functionality of saving HabitTranslation in HabitServiceImpl;

### CODE REVIEW

File: service/src/main/java/greencity/mapping/HabitTranslationMapper.java [hunk 1]
```diff
@@ -29,4 +60,22 @@ protected HabitTranslation convert(HabitTranslationDto habitTranslationDto) {
...
+     *
+     * @param dtoList  {@link List} of {@link HabitTranslationDto}
+     * @param language {@link String}
+     *
+     * @return {@link List} of {@link HabitTranslation}
+     *
+     * @author Chernenko Vitaliy
+     */
+    public List<HabitTranslation> mapAllToList(List<HabitTranslationDto> dtoList, String language) {
+        if (language.equals("ua")) {
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/mapping/HabitTranslationMapper.java]: please move `ua` to the constant and compare like this to prevent NPE
`"ua".equals(language)`

File: service/src/main/java/greencity/service/HabitServiceImpl.java [hunk 2]
```diff
@@ -491,21 +491,26 @@ private void updateHabitTranslationsForCustomHabit(CustomHabitDtoRequest habitDt
     }
 
     private void saveHabitTranslationListsToHabitTranslationRepo(CustomHabitDtoRequest habitDto, Habit habit) {
-        List<HabitTranslation> habitTranslationListForUa = mapHabitTranslationFromAddCustomHabitDtoRequest(habitDto);
+        final String UA = "ua";
+        final String EN = "en";
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/HabitServiceImpl.java]: please move to the constants

File: service/src/main/java/greencity/mapping/HabitTranslationMapper.java [hunk 3]
```diff
@@ -18,6 +18,37 @@ protected HabitTranslation convert(HabitTranslationDto habitTranslationDto) {
...
+     * fields if they not null.
+     *
+     * @param habitTranslationDto {@link HabitTranslationDto}
+     * @return {@link HabitTranslation}
+     *
+     * @author Chernenko Vitaliy
+     */
+    public HabitTranslation convertUa(HabitTranslationDto habitTranslationDto) {
+        HabitTranslation habitTranslation = new HabitTranslation();
+        if (habitTranslationDto.getNameUa() == null) {
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/mapping/HabitTranslationMapper.java]: that logic can be simplified using  [defaultIfNull](https://commons.apache.org/proper/commons-lang/javadocs/api-3.1/src-html/org/apache/commons/lang3/ObjectUtils.html#line.93)

**Comment by RomaMocherniuk** [comment]
Please increase test coverage to at least 90%
image

**Review by Maryna-511750 — APPROVED** [review]

**Review by Cr1stal423 — APPROVED** [review]

File: service/src/main/java/greencity/mapping/HabitTranslationMapper.java (hunk 1 above)
Comment (ChernenkoVitaliy) [reply service/src/main/java/greencity/mapping/HabitTranslationMapper.java]: Good point. I'll remember it.
Fixed.

File: service/src/main/java/greencity/service/HabitServiceImpl.java (hunk 2 above)
Comment (ChernenkoVitaliy) [reply service/src/main/java/greencity/service/HabitServiceImpl.java]: Thanks. Done

File: service/src/main/java/greencity/mapping/HabitTranslationMapper.java (hunk 3 above)
Comment (ChernenkoVitaliy) [reply service/src/main/java/greencity/mapping/HabitTranslationMapper.java]: Very useful thing. I think I'll use it in the future.
Thanks. Fixed.

**Comment by ChernenkoVitaliy** [comment]
> Please increase test coverage to at least 90% image

Thanks. Improved.
For now 100% covered.

**Review by KizerovDmitriy — APPROVED** [review]

**Review by RomaMocherniuk — APPROVED** [review]
