### PR TITLE
[My Habits] User can't 'unmark' inprogress habits that were acquired onest

### LINKED ISSUE #5561: [My Habits] User can't 'unmark' inprogress habits that were acquired ones
**Environment:** Windows 10 Pro, Google Chrome 111.0.5563.112
**Reproducible:** always
**Build found:** 29.03.2023

**Preconditions**
User is authorized
User have at least one acquired habit and the same one inprogress

**Steps to reproduce**
1. Go to https://greencity.testgreencity.ga/swagger-ui.html#
2. Find **habit-assign-controller**
3. Controller POST/habit/assign/{habitId}/unenroll/{date}
image

**Actual result**
Button Unmark habit don't work

**Expected result**
After mark habit user can unmark habit
Controller POST/habit/assign/**{habitId}**/enroll/{date} work by **habitAssignId**

### PR DESCRIPTION
**Pull request by sergoliarnik**
## Summary Of Issue :
Refactor POST/habit/assign/{habitId}/unenroll/{date}, so it accepts habitAssignId instead habitId

**Issue Link**
https://github.com/ita-social-projects/GreenCity/issues/5561

## Summary Of Changes :
1) refactor unenrollHabit controller method and service method
2) refactored old tests and add new ones

## CHECK LIST
- [x] Code is up-to-date with the `dev` branch.
- [x] You've successfully built and run the tests locally.
- [x] There are new or updated unit tests validating the change.
- [x] JIRA/ Github Issue number & title in PR title (ISSUE-: Ticket title)
- [x] This template filled (above this section).
- [x] Sonar's report does not contain bugs, vulnerabilities, security issues, code smells ar duplication
- [x] All files reviewed before sending to reviewers

### CODE REVIEW

File: service/src/test/java/greencity/service/HabitAssignServiceImplTest.java [hunk 1]
```diff
@@ -100,6 +101,8 @@ class HabitAssignServiceImplTest {
     @Mock
     CustomShoppingListItemRepo customShoppingListItemRepo;
     @Mock
+    HabitStatusCalendarRepo habitStatusCalendarRepo;
```
Comment (RomaMocherniuk) [inline service/src/test/java/greencity/service/HabitAssignServiceImplTest.java]: could be `private`

**Review by RomaMocherniuk — APPROVED** [review]

**Review by KharchenkoV — APPROVED** [review]

**Review by juseti — APPROVED** [review]

**Review by Maksym-Lenets — APPROVED** [review]
