### PR TITLE
#5855 [GreenCity] Add formatted address field to EventDateLocation Address

### LINKED ISSUE #5855: [GreenCity] Add Google API formattedAddress field to EventDateLocation Address
**Preconditions**
If we create an event with a location that doesn't contain a street name or house number, we get "null" in the location field.

**Steps to reproduce**
1. Log in as a user.
2. Go to the Events tab.
3. Create and save a new event with a location that includes the street address.
4. Update this event with a location without a street name.

**Actual result**
"Null" in empty address parts.

**Expected result**
Use formatted address from Google API if street name is empty.

### PR DESCRIPTION
**Pull request by Maksym-Lenets**
## Summary Of Issue :
Some of the addresses returned by Google Api may not contain the "root" (street) name attribute, in this case we can use the formatted address that contains the most complete information about the address.

**Issue Link**
https://github.com/ita-social-projects/GreenCity/issues/5855

## Summary Of Changes :
1) Added formattedAddress field to Address entity and all associated DTOs.
2) Updated mappers.
3) Updated existing tests.
4) Updated liqubase changelog with new fields for events_dates_locations table.

## CHECK LIST
- [x] Code is up-to-date with the `dev` branch.
- [x] You've successfully built and run the tests locally.
- [x] There are new or updated unit tests validating the change.
- [x] JIRA/ Github Issue number & title in PR title (ISSUE-: Ticket title)
- [x] This template filled (above this section).
- [x] Sonar's report does not contain bugs, vulnerabilities, security issues, code smells or duplication
- [x] All files reviewed before sending to reviewers

### CODE REVIEW

File: service/src/main/java/greencity/service/GoogleApiService.java [hunk 1]
```diff
@@ -80,16 +80,18 @@ private AddressResponse getAddressResponseByLocaleAndCoordinates(LatLng latLng,
         try {
             GeocodingResult[] results = GeocodingApi.newRequest(context)
                 .latlng(latLng).language(locale.getLanguage()).await();
-            return getAddressResponse(results[0].addressComponents);
+            return getAddressResponse(results[0]);
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/GoogleApiService.java:83]: Can we have the `IndexOutOfBound` exception here?

Comment (Maksym-Lenets) [reply service/src/main/java/greencity/service/GoogleApiService.java:83]: No
If the geocoding was successful but returned no results, the ApiException (ZeroResultsException) is thrown and caught below.

**Review by ABbondar — APPROVED** [review]

**Review by sergoliarnik — APPROVED** [review]

**Review by Markiro1 — APPROVED** [review]

**Review by juseti — APPROVED** [review]
